#!/bin/sh
git clone http://github.com/z0mbix/vim-shfmt.git
git clone http://github.com/sheerun/vim-polyglot.git
git clone http://github.com/vim-pandoc/vim-pandoc.git
git clone http://github.com/rwxrob/vim-pandoc-syntax-simple.git
git clone http://github.com/cespare/vim-toml.git
git clone http://github.com/pangloss/vim-javascript.git
git clone http://github.com/fatih/vim-go.git
git clone http://github.com/PProvost/vim-ps1.git
git clone http://github.com/tpope/vim-fugitive.git
git clone http://github.com/morhetz/gruvbox.git
git clone http://github.com/roxma/vim-tmux-clipboard.git
